#ifndef _USB_HID_KEYBOARD_H_
#define _USB_HID_KEYBOARD_H_ 1
#include <usb/hid.h>



#define USB_HID_KEYBOARD_LCTRL "\xf0"
#define USB_HID_KEYBOARD_LSHIFT "\xf2"
#define USB_HID_KEYBOARD_LALT "\xf4"
#define USB_HID_KEYBOARD_LSUPER "\xf6"
#define USB_HID_KEYBOARD_RCTRL "\xf8"
#define USB_HID_KEYBOARD_RSHIFT "\xfa"
#define USB_HID_KEYBOARD_RALT "\xfc"
#define USB_HID_KEYBOARD_RSUPER "\xfe"

#define USB_HID_KEYBOARD_NO_LCTRL "\xf1"
#define USB_HID_KEYBOARD_NO_LSHIFT "\xf3"
#define USB_HID_KEYBOARD_NO_LALT "\xf5"
#define USB_HID_KEYBOARD_NO_LSUPER "\xf7"
#define USB_HID_KEYBOARD_NO_RCTRL "\xf9"
#define USB_HID_KEYBOARD_NO_RSHIFT "\xfb"
#define USB_HID_KEYBOARD_NO_RALT "\xfd"
#define USB_HID_KEYBOARD_NO_RSUPER "\xff"

#define USB_HID_KEYBOARD_EUROPE_1 "\x80"
#define USB_HID_KEYBOARD_CAPS_LOCK "\x87"
#define USB_HID_KEYBOARD_F1 "\x88"
#define USB_HID_KEYBOARD_F2 "\x89"
#define USB_HID_KEYBOARD_F3 "\x8a"
#define USB_HID_KEYBOARD_F4 "\x8b"
#define USB_HID_KEYBOARD_F5 "\x8c"
#define USB_HID_KEYBOARD_F6 "\x8d"
#define USB_HID_KEYBOARD_F7 "\x8e"
#define USB_HID_KEYBOARD_F8 "\x8f"
#define USB_HID_KEYBOARD_F9 "\x90"
#define USB_HID_KEYBOARD_F10 "\x91"
#define USB_HID_KEYBOARD_F11 "\x92"
#define USB_HID_KEYBOARD_F12 "\x93"
#define USB_HID_KEYBOARD_PRINT_SCREEN "\x94"
#define USB_HID_KEYBOARD_SCROLL_LOCK "\x95"
#define USB_HID_KEYBOARD_PAUSE "\x96"
#define USB_HID_KEYBOARD_INSERT "\x97"
#define USB_HID_KEYBOARD_HOME "\x98"
#define USB_HID_KEYBOARD_PAGE_UP "\x99"
#define USB_HID_KEYBOARD_DELETE "\x9a"
#define USB_HID_KEYBOARD_END "\x9b"
#define USB_HID_KEYBOARD_PAGE_DOWN "\x9c"
#define USB_HID_KEYBOARD_ARROW_RIGHT "\x9d"
#define USB_HID_KEYBOARD_ARROW_LEFT "\x9e"
#define USB_HID_KEYBOARD_ARROW_DOWN "\x9f"
#define USB_HID_KEYBOARD_ARROW_UP "\xa0"
#define USB_HID_KEYBOARD_NUM_LOCK "\xa1"
#define USB_HID_KEYBOARD_KEYPAD_DIVIDE "\xa2"
#define USB_HID_KEYBOARD_KEYPAD_MULTIPLY "\xa3"
#define USB_HID_KEYBOARD_KEYPAD_SUBTRACT "\xa4"
#define USB_HID_KEYBOARD_KEYPAD_ADD "\xa5"
#define USB_HID_KEYBOARD_KEYPAD_ENTER "\xa6"
#define USB_HID_KEYBOARD_KEYPAD_1 "\xa7"
#define USB_HID_KEYBOARD_KEYPAD_2 "\xa8"
#define USB_HID_KEYBOARD_KEYPAD_3 "\xa9"
#define USB_HID_KEYBOARD_KEYPAD_4 "\xaa"
#define USB_HID_KEYBOARD_KEYPAD_5 "\xab"
#define USB_HID_KEYBOARD_KEYPAD_6 "\xac"
#define USB_HID_KEYBOARD_KEYPAD_7 "\xad"
#define USB_HID_KEYBOARD_KEYPAD_8 "\xae"
#define USB_HID_KEYBOARD_KEYPAD_9 "\xaf"
#define USB_HID_KEYBOARD_KEYPAD_0 "\xb0"
#define USB_HID_KEYBOARD_KEYPAD_DECIMAL "\xb1"
#define USB_HID_KEYBOARD_EUROPE_2 "\xb2"
#define USB_HID_KEYBOARD_APPLICATION "\xb3"
#define USB_HID_KEYBOARD_POWER "\xb4"
#define USB_HID_KEYBOARD_KEYPAD_EQUAL "\xb5"
#define USB_HID_KEYBOARD_F13 "\xb6"
#define USB_HID_KEYBOARD_F14 "\xb7"
#define USB_HID_KEYBOARD_F15 "\xb8"
#define USB_HID_KEYBOARD_F16 "\xb9"
#define USB_HID_KEYBOARD_F17 "\xba"
#define USB_HID_KEYBOARD_F18 "\xbb"
#define USB_HID_KEYBOARD_F19 "\xbc"
#define USB_HID_KEYBOARD_F20 "\xbd"
#define USB_HID_KEYBOARD_F21 "\xbe"
#define USB_HID_KEYBOARD_F22 "\xbf"
#define USB_HID_KEYBOARD_F23 "\xc0"
#define USB_HID_KEYBOARD_F24 "\xc1"
#define USB_HID_KEYBOARD_EXECUTE "\xc2"
#define USB_HID_KEYBOARD_HELP "\xc3"
#define USB_HID_KEYBOARD_MENU "\xc4"
#define USB_HID_KEYBOARD_SELECT "\xc5"
#define USB_HID_KEYBOARD_STOP "\xc6"
#define USB_HID_KEYBOARD_AGAIN "\xc7"
#define USB_HID_KEYBOARD_UNDO "\xc8"
#define USB_HID_KEYBOARD_CUT "\xc9"
#define USB_HID_KEYBOARD_COPY "\xca"
#define USB_HID_KEYBOARD_PASTE "\xcb"
#define USB_HID_KEYBOARD_FIND "\xcc"
#define USB_HID_KEYBOARD_MUTE "\xcd"
#define USB_HID_KEYBOARD_VOLUME_UP "\xce"
#define USB_HID_KEYBOARD_VOLUME_DOWN "\xcf"
#define USB_HID_KEYBOARD_LOCKING_CAPS_LOCK "\xd0"
#define USB_HID_KEYBOARD_LOCKING_NUM_LOCK "\xd1"
#define USB_HID_KEYBOARD_LOCKING_SCROLL_LOCK "\xd2"
#define USB_HID_KEYBOARD_KEYPAD_COMMA "\xd3"
#define USB_HID_KEYBOARD_KEYPAD_EQUAL_SIGN "\xd4"



#define USB_HID_KEYBOARD_REPORT \
	USB_HID_TAG1(USB_HID_RI_GLOBAL_USAGE_PAGE,USB_HID_USAGE_PAGE_DESKTOP), \
	USB_HID_TAG1(USB_HID_RI_LOCAL_USAGE,USB_HID_USAGE_DESKTOP_KEYBOARD), \
	USB_HID_TAG1(USB_HID_RI_MAIN_COLLECTION,USB_HID_COLLECTION_APPLICATION), \
	\
	USB_HID_TAG1(USB_HID_RI_GLOBAL_USAGE_PAGE,USB_HID_USAGE_PAGE_KEYBOARD), \
	USB_HID_TAG1(USB_HID_RI_LOCAL_USAGE_MIN,224), \
	USB_HID_TAG1(USB_HID_RI_LOCAL_USAGE_MAX,231), \
	USB_HID_TAG1(USB_HID_RI_GLOBAL_LOGICAL_MIN,0), \
	USB_HID_TAG1(USB_HID_RI_GLOBAL_LOGICAL_MAX,1), \
	USB_HID_TAG1(USB_HID_RI_GLOBAL_REPORT_COUNT,8), \
	USB_HID_TAG1(USB_HID_RI_GLOBAL_REPORT_SIZE,1), \
	USB_HID_TAG1(USB_HID_RI_MAIN_INPUT,USB_HID_VARIABLE), \
	\
	USB_HID_TAG1(USB_HID_RI_GLOBAL_REPORT_COUNT,1), \
	USB_HID_TAG1(USB_HID_RI_GLOBAL_REPORT_SIZE,8), \
	USB_HID_TAG1(USB_HID_RI_MAIN_INPUT,USB_HID_CONSTANT), \
	\
	USB_HID_TAG1(USB_HID_RI_GLOBAL_USAGE_PAGE,USB_HID_USAGE_PAGE_LED), \
	USB_HID_TAG1(USB_HID_RI_LOCAL_USAGE_MIN,1), \
	USB_HID_TAG1(USB_HID_RI_LOCAL_USAGE_MAX,5), \
	USB_HID_TAG1(USB_HID_RI_GLOBAL_REPORT_COUNT,5), \
	USB_HID_TAG1(USB_HID_RI_GLOBAL_REPORT_SIZE,1), \
	USB_HID_TAG1(USB_HID_RI_MAIN_OUTPUT,USB_HID_VARIABLE), \
	\
	USB_HID_TAG1(USB_HID_RI_GLOBAL_REPORT_COUNT,1), \
	USB_HID_TAG1(USB_HID_RI_GLOBAL_REPORT_SIZE,3), \
	USB_HID_TAG1(USB_HID_RI_MAIN_OUTPUT,USB_HID_CONSTANT), \
	\
	USB_HID_TAG1(USB_HID_RI_GLOBAL_USAGE_PAGE,USB_HID_USAGE_PAGE_KEYBOARD), \
	USB_HID_TAG1(USB_HID_RI_LOCAL_USAGE_MIN,0), \
	USB_HID_TAG2(USB_HID_RI_LOCAL_USAGE_MAX,255), \
	USB_HID_TAG1(USB_HID_RI_GLOBAL_LOGICAL_MIN,0), \
	USB_HID_TAG2(USB_HID_RI_GLOBAL_LOGICAL_MAX,255), \
	USB_HID_TAG1(USB_HID_RI_GLOBAL_REPORT_COUNT,6), \
	USB_HID_TAG1(USB_HID_RI_GLOBAL_REPORT_SIZE,8), \
	USB_HID_TAG1(USB_HID_RI_MAIN_INPUT,0), \
	\
	USB_HID_TAG0(USB_HID_RI_MAIN_COLLECTION_END)



void usb_hid_keyboard_type_keys(uint8_t endpoint,const char* string,uint8_t interval);



#endif
